---
- name: Initial configuration Raspberry Pi Ubuntu Server 20.04
  
  tasks:
    - name: Update and upgrade the system
  hosts: '{{inventory}}'
    become: yes
    shell: ping -c1 www.shellhacks.com
