---
- name: Initial server configuration
  hosts: stage
  become: true

  tasks:
    - name: Update cache and upgrade all packages
      register: updatesys
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Display the last line of the previous task to check the stats
      debug:
        msg:  "{{updatesys.stdout_lines|last}}"

    - name: Configure the PoE HAT fan thresholds
      ansible.builtin.blockinfile:
        path: /boot/firmware/config.txt
        block: |
          # PoE Hat Fan Speeds
          dtoverlay=rpi-poe
          dtparam=poe_fan_temp0=65000
          dtparam=poe_fan_temp1=74000
          dtparam=poe_fan_temp2=76000
          dtparam=poe_fan_temp3=81000
        
    - name: Check if reboot is needed
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"

    - name: Add FQDN to /etc/hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: '127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}'
        state: present

